### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by inigomarquinez** [onebeyond/license-checker#29]
# Roadmap

This is the roadmap of the desired features to be included in this package from more to less priority:

## 🐛  Bug fixes
- [ ] Fix bug to do a case insensitive comparison (#21)

## 🆕  Enhancements
- [ ] Include license list from less to more restrictive (#3)
- [x] Add regular expression to match forbidden licenses instead of a complete list of possible values (eg. AGPL* instead of AGPL-2.0, AGPL-3.0) (#20)
- [ ] Compare number of licenses used with number of packages installed (#1)
- [ ] Check allow licenses instead of forbidden ones (#24)
- [X] Adding --disableReport cli option (#12)
- [X] Add a new option to send a custom header to be included in the report (#22)

## 🔝 Good practices
- [x] Add tests (#4)
- [X] Add linter (#25)
- [X] Add a release builder (#27)

**Comment by inigomarquinez** [comment]
We have moved the roadmap to https://github.com/orgs/onebeyond/projects/13/views/1, so we can close this issue.
